//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telligent.Evolution.Extensions.SharePoint.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://telligentsharepoint.sharepoint.com/_vti_bin/TaxonomyClientService.asmx")]
        public string Telligent_Evolution_Extensions_SharePoint_WebServices_TaxonomyClientService_Taxonomy_x0020_web_x0020_service {
            get {
                return ((string)(this["Telligent_Evolution_Extensions_SharePoint_WebServices_TaxonomyClientService_Taxon" +
                    "omy_x0020_web_x0020_service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://telligentsharepoint.sharepoint.com/_vti_bin/UserProfileChangeService.asmx" +
            "")]
        public string Telligent_Evolution_Extensions_SharePoint_WebServices_UserProfileChangeService_UserProfileChangeService {
            get {
                return ((string)(this["Telligent_Evolution_Extensions_SharePoint_WebServices_UserProfileChangeService_Us" +
                    "erProfileChangeService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://telligentsharepoint.sharepoint.com/_vti_bin/UserProfileService.asmx")]
        public string Telligent_Evolution_Extensions_SharePoint_WebServices_UserProfileService_UserProfileService {
            get {
                return ((string)(this["Telligent_Evolution_Extensions_SharePoint_WebServices_UserProfileService_UserProf" +
                    "ileService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://telligentsharepoint.sharepoint.com/_vti_bin/Versions.asmx")]
        public string Telligent_Evolution_Extensions_SharePoint_WebServices_VersionsService_Versions {
            get {
                return ((string)(this["Telligent_Evolution_Extensions_SharePoint_WebServices_VersionsService_Versions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://telligentsharepoint.sharepoint.com/_vti_bin/lists.asmx")]
        public string Telligent_Evolution_Extensions_SharePoint_WebServices_SPListsService_Lists {
            get {
                return ((string)(this["Telligent_Evolution_Extensions_SharePoint_WebServices_SPListsService_Lists"]));
            }
        }
    }
}
